#!/bin/sh

COMPOSE_PREFIX=minecraft-manager-docker
SRC=data
DST=${1:-`date +%Y%m%d_%H%M%S`}.tar.bz2

docker-compose down

TEMP_CONTAINER=$(docker run -itd --mount source=${COMPOSE_PREFIX}_minecraft_data,destination=/${SRC},readonly alpine)
docker exec ${TEMP_CONTAINER} tar jcvf /root/${DST} ${SRC}
docker cp ${TEMP_CONTAINER}:/root/${DST} ./
docker rm -f ${TEMP_CONTAINER}

docker-compose up -d
