version: "2"
services:
  minecraft-server:
    container_name: minecraft
    environment:
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "TRUE"
      DIFFICULTY: hard
      EULA: "TRUE"
      FORCE_GAMEMODE: "TRUE"
      INIT_MEMORY: 2880M
      MAX_MEMORY: 2880M
      MAX_PLAYERS: 5
      MAX_WORLD_SIZE: 16384
      MOTD: Server by kurone-kito
      OPS: ${OPS}
      PVP: "FALSE"
      SEED: ${SEED}
      VIEW_DISTANCE: 9
    image: itzg/minecraft-server
    mem_limit: "3.5G"
    ports:
      - "25565:25565"
    stdin_open: true
    restart: always
    tty: true
    volumes:
      - minecraft_data:/data

volumes:
  minecraft_data:
