#!/bin/sh
# vim: set ft=sh :

set -eu
cd $(dirname $0)

ecs-cli configure --cluster kito-ecs --region ap-northeast-1 --default-launch-type EC2
ecs-cli up --keypair AWS --capability-iam --instance-type t2.medium
