#!/bin/sh

if [ $# -lt 1 ]; then
    echo "Usage: ./restore 20190810_114514.tar.bz2" >&2
    exit 255
fi
if [ ! -f $1 ] || [ ! -r $1 ]; then
    echo "File: ${1} is not found." >&2
    exit 1
fi
FILENAME=`basename $1`
if [ ! -f ${FILENAME} ] || [ ! -r ${FILENAME} ]; then
    echo "File: ${FILENAME} is not found in here." >&2
    exit 2
fi

COMPOSE_PREFIX=minecraft-manager-docker
DST=data

docker-compose down

TEMP_CONTAINER=$(docker run -itd --mount source=${COMPOSE_PREFIX}_minecraft_data,destination=/${DST} alpine)
docker cp ./${FILENAME} ${TEMP_CONTAINER}:/root/
docker exec ${TEMP_CONTAINER} tar jxvf /root/${FILENAME} ${SRC}
docker rm -f ${TEMP_CONTAINER}

docker-compose up -d
